language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" 
  - "nightly" 
os:
  - linux
  - osx
before-script: 
  - mv 8varinterpreter.py 8var
  - chmod +x 8var
script: 8var test.8v
